
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100),
    age INT
);


INSERT INTO users (name, age)
VALUES
    ('Juan Perez', 25),
    ('Maria Gomez', 32),
    ('Carlos Ruiz', 40),
    ('Laura Diaz', 28),
    ('Pedro Martinez', 34),
    ('Ana Lopez', 30),
    ('Jose Torres', 45),
    ('Lucia Sanchez', 22),
    ('David Garcia', 38),
    ('Marta Fernandez', 29),
    ('Antonio Romero', 36),
    ('Isabel Hernandez', 41),
    ('Luis Perez', 33),
    ('Eva Ruiz', 27),
    ('Jorge Gonzalez', 42),
    ('Beatriz Morales', 39),
    ('Francisco Jimenez', 26),
    ('Elena Ramos', 31),
    ('Manuel Ortiz', 35),
    ('Carmen Vazquez', 43),
    ('Raul Perez', 24),
    ('Alba Torres', 37),
    ('Victor Lopez', 47),
    ('Patricia Garcia', 50),
    ('Ricardo Diaz', 44),
    ('Marina Fernandez', 29),
    ('Felipe Gomez', 48),
    ('Sandra Ramirez', 32),
    ('Angel Sanchez', 26),
    ('Teresa Martinez', 41),
    ('Diego Hernandez', 28),
    ('Victoria Romero', 45),
    ('Pablo Ruiz', 31),
    ('Sofia Jimenez', 30),
    ('Manuela Gonzalez', 36),
    ('Daniel Fernandez', 33),
    ('Alicia Ortiz', 29),
    ('Sergio Garcia', 39),
    ('Miriam Perez', 27),
    ('Rosa Lopez', 32),
    ('Tomás Vazquez', 38),
    ('Adriana Romero', 31),
    ('Juan Carlos Sanchez', 43),
    ('Nuria Torres', 30),
    ('Guillermo Diaz', 37),
    ('Gloria Ruiz', 33),
    ('Joaquín Hernandez', 41),
    ('Susana Garcia', 35),
    ('Luis Romero', 29),
    ('Esther Perez', 40),
    ('Antonio Vasquez', 32),
    ('Clara Sanchez', 34),
    ('Luis Felipe Garcia', 39),
    ('Alicia Romero', 28),
    ('Fernando Ruiz', 45),
    ('Marisa Torres', 30),
    ('Julian Fernandez', 33),
    ('Cristina Gonzalez', 38),
    ('Ricardo Ortiz', 41),
    ('Lorena Lopez', 36),
    ('Carlos Vazquez', 27),
    ('Santiago Garcia', 44),
    ('Dolores Sanchez', 29),
    ('Raul Romero', 34),
    ('Antonio Lopez', 39),
    ('Cecilia Perez', 42),
    ('Manuel Garcia', 38),
    ('Ines Fernandez', 32),
    ('Jesus Torres', 31),
    ('Isabel Jimenez', 28),
    ('David Vazquez', 40),
    ('Belen Lopez', 33),
    ('Fernando Perez', 29),
    ('Dolores Ruiz', 32),
    ('Eduardo Martinez', 41),
    ('Lidia Sanchez', 37),
    ('Felipe Hernandez', 26),
    ('Nuria Romero', 33),
    ('Ramón Perez', 28),
    ('Andrea Garcia', 35),
    ('Lucas Jimenez', 29),
    ('Elena Lopez', 30),
    ('Santiago Ruiz', 38),
    ('Lourdes Sanchez', 31),
    ('Oscar Romero', 34),
    ('Juan Fernandez', 40),
    ('Lucia Vazquez', 29),
    ('Carlos Perez', 36),
    ('Maria Dolores Torres', 37),
    ('Antonio Sanchez', 28),
    ('Roberto Jimenez', 33),
    ('Carlos Romero', 35),
    ('Victoria Vazquez', 39),
    ('Marta Perez', 33),
    ('Antonio Lopez', 30),
    ('Carlos Vasquez', 27),
    ('Carolina Jimenez', 32),
    ('Sofia Torres', 31),
    ('Cristina Perez', 33),
    ('Pedro Garcia', 36),
    ('David Romero', 35),
    ('Eugenia Lopez', 28),
    ('Alfonso Ruiz', 40),
    ('Olga Sanchez', 34),
    ('Juan Antonio Hernandez', 31),
    ('Maria Teresa Torres', 29),
    ('Santiago Romero', 37),
    ('Ana Ruiz', 33),
    ('Nuria Garcia', 30),
    ('Elena Sanchez', 39),
    ('Carlos Fernandez', 34),
    ('Antonio Perez', 35),
    ('Alba Ruiz', 33),
    ('Javier Jimenez', 28),
    ('Rafael Romero', 37),
    ('Sandra Sanchez', 29),
    ('Laura Vasquez', 36),
    ('Miguel Perez', 28),
    ('Teresa Ruiz', 30),
    ('Roberto Fernandez', 32),
    ('Jose Maria Torres', 38),
    ('Eva Jimenez', 33),
    ('Irene Perez', 35),
    ('Carlos Lopez', 32),
    ('Silvia Ruiz', 29),
    ('Martín Garcia', 41),
    ('Maria Perez', 30);
